Do Not Merge Testing Pipeline Fscloud
terraform-ibm-modules/terraform-ibm-base-ocp-vpc pull request #147
Opened 2023-04-26 13:01 UTC by daniel-butler-irl

### Description

Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.

### Types of changes in this PR

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

2023-04-28 09:16 UTC, ocofaigh commented on cra-tf-validate-ignore-rules.json
> +      "ignore_reason": "This is restricting by CBR, not IP range. This is not yet checked by the scan Tracked: AHA SCC-961",
Perhaps lets be a little clearer here...

This module supports restricting network access using Context Based Restrictions (CBRs), however SCC does not yet support scanning for CBR rules, so hence the rule currently fails. SCC CBR support is being tracked in AHA SCC-961

2023-05-02 19:17 UTC, ocofaigh commented on .github/workflows/ci.yml
> +    types: [opened, synchronize, reopened, ready_for_review]
I'm guessing this was to try and prevent pipeline from running on draft PRs? However, @rajatagarwal-ibm made the same change in mongoDB module, and it doesn't work. I created a draft PR and it ran the pipeline. See https://github.com/terraform-ibm-modules/terraform-ibm-icd-mongodb/pull/153

2023-05-04 10:41 UTC, ocofaigh commented on .github/workflows/ci.yml
> +    types: [opened, synchronize, reopened, ready_for_review]
As per scrum discussions, further pipeline changes required for this to work

2023-05-04 11:10 UTC, ocofaigh requested changes
Left some comments

2023-05-04 11:10 UTC, ocofaigh commented on profiles/fscloud/variables.tf
> +  #   default     = "Normal"
this can actually now be set to Normal since you have bumped the IBM provider version. We can set it in root module too

2023-05-04 11:10 UTC, ocofaigh commented on profiles/fscloud/variables.tf
> +  description = "APIkey that's associated with the account to use, set via environment variable TF_VAR_ibmcloud_api_key"
remove the text `set via environment variable TF_VAR_ibmcloud_api_key` as this doesn't make sense in a schematics or projects world

2023-05-04 11:10 UTC, ocofaigh commented on profiles/fscloud/README.md
> +## Note: If no Context Based Restriction(CBR) rules are passed, you must configure Context Based Restrictions externally to be compliant.
This readme need to have the terradocs metadata tags to populate the input and outputs as this is a callable module itself

2023-05-04 11:10 UTC, ocofaigh commented on profiles/fscloud/README.md
> +      cross region support and KYOK encryption but CRA does not pick this up.
These seem to be from SCC v1 goals. Can we update with SCC v2/v3 rules ?

2023-05-04 11:10 UTC, ocofaigh commented on examples/fscloud/variables.tf
> +}
Do vpc's have to have a unique name? If so, I suggest removing this variable, and hard code the vpc name in the main.tf of the example using the prefix variable

2023-05-04 11:11 UTC, ocofaigh commented on profiles/fscloud/variables.tf
> +  description = "The COS id of an already existing COS instance. Only required if 'use_existing_cos = true'"
If not, we could mandate that cos instance has to be passed ?

2023-06-01 13:23 UTC, ocofaigh requested changes
see final comments

2023-06-01 13:23 UTC, ocofaigh commented on profiles/fscloud/variables.tf
> +  default     = null
this should be required for fscloud right? so remove default value

2023-06-01 13:23 UTC, ocofaigh commented on profiles/fscloud/variables.tf
> +  validation {
does the validation from the main module carry over here? Just thinking maybe remove it to avoid having to maintain in 2 places?

2023-06-01 13:23 UTC, ocofaigh commented on profiles/fscloud/variables.tf
> +  description = "Metadata labels describing this cluster deployment, i.e. test"
maybe remove `i.e. test` ?

2023-06-01 13:23 UTC, ocofaigh commented on examples/fscloud/README.md
> +- A context-based restriction (CBR) rule to only allow COS Instance to be accessible from within the VPC
COS Instance should be OCP cluster ?

2023-06-01 13:23 UTC, ocofaigh commented on tests/pr_test.go
> +		Prefix:       "base-ocp-fscloud",
Do you want to maybe leave a comment here explaining why we don't pass an existing resource group (for example like this: https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/blob/main/tests/pr_test.go#L46-L51

2023-06-01 13:23 UTC, ocofaigh commented on cra-tf-validate-ignore-rules.json
> +      "scc_rule_id": "rule-8cbd597c-7471-42bd-9c88-36b2696456e9",
Where in the code are we creating a bucket? Id on't think we are, so why would CRA have to ignore this rule? We only create an instance (OCP creates the bucket but terraform plan has no notion of this)

2023-06-13 10:57 UTC, daniel-butler-irl commented
/run pipeline

2023-06-13 11:17 UTC, daniel-butler-irl commented
/run pipeline

2023-06-23 19:49 UTC, ocofaigh requested changes
IKS have confirmed that they will auto create the KMS auth policy (both for Key Protect and HPCS) so please remove anything related to auth policy set up in this PR

2023-07-25 11:39 UTC, daniel-butler-irl commented
/run pipeline

2023-07-31 11:56 UTC, daniel-butler-irl commented
/run pipeline

2023-08-01 16:06 UTC, ocofaigh requested changes
Looking good - just a few minor comments

2023-08-01 16:06 UTC, ocofaigh commented on examples/fscloud/main.tf
> +      pool_name         = "default" # ibm_container_vpc_cluster automatically names standard pool "standard" (See https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2849)
"standard" -> "default" (I think someone did a find and replace and accidentally updated this in other examples at some point)

2023-08-01 16:06 UTC, ocofaigh commented on examples/fscloud/variables.tf
> +
As per deep dive discussions today, should you remove some of these vars from the example and add directly into the main.tf ?

2023-08-01 16:06 UTC, ocofaigh commented on modules/fscloud/variables.tf
> +  #   default     = "Normal"
you can remove this comment, we are going to stick with "IngressReady" as the default

2023-08-01 16:06 UTC, ocofaigh commented on examples/fscloud/variables.tf
> +  default     = "4.12"
Did we try 4.13 and it failed? We should probably add a code comment here saying we need to lock into 4.12 for now, but it should be set back to `null` to allow latest to always run in the tests - maybe create git issue too or we will never remember to come back to it

2023-08-02 14:28 UTC, daniel-butler-irl commented
/run pipeline

2023-08-02 14:29 UTC, daniel-butler-irl commented on cra-tf-validate-ignore-rules.json
>              "ignore_reason": "Rule is related to VPC, not OCP Clusters",
@ocofaigh all these rules can be removed after this is merged, just incase I forget...

2023-08-02 14:37 UTC, daniel-butler-irl commented
/run pipeline

2023-08-02 14:57 UTC, daniel-butler-irl commented
/run pipeline

2023-08-02 15:33 UTC, ocofaigh approved these changes

2023-08-02 15:40 UTC, ocofaigh approved these changes

2023-08-02 17:10 UTC, ocofaigh requested changes
@daniel-butler-irl Looks like the resource_tags variable is missing from the fscloud example:
```
TestFSCloudExample 2023-08-02T15:05:52Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: Value for undeclared variable
│ 
│ A variable named "resource_tags" was assigned on the command line, but the
│ root module does not declare a variable of that name. To use this value,
│ add a "variable" block to the configuration.
╵}
```

2023-08-02 21:07 UTC, daniel-butler-irl commented
/run pipeline

2023-08-03 05:55 UTC, daniel-butler-irl commented
/run pipeline

2023-08-03 08:42 UTC, ocofaigh approved these changes

2023-08-03 08:42 UTC, merged

2023-08-03 08:44 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 3.6.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/releases/tag/v3.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: