tests: add test for custom sg
terraform-ibm-modules/terraform-ibm-base-ocp-vpc pull request #362
Opened 2024-02-08 00:47 UTC by jor2

### Description

Create test for custom_sg example

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Create a test that implements the custom_sg example.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-02-09 12:49 UTC, ocofaigh commented on tests/other_test.go
> +			"ocp_version": ocpVersion2,
this feature is only available in OCP 4.14, so you need to change this to `ocpVersion1`

2024-02-09 12:50 UTC, ocofaigh requested changes
see comment

2024-02-09 13:34 UTC, jor2 commented
/run pipeline

2024-02-09 14:57 UTC, jor2 commented
> see comment

passed locally

<img width="1193" alt="Screenshot 2024-02-09 at 14 56 40" src="https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/assets/22322183/b103c73c-232a-4c8f-b08a-a58bcd592cf2">

2024-02-09 15:28 UTC, ocofaigh approved these changes

2024-02-09 15:28 UTC, merged

2024-02-12 10:13 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 3.16.2 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/releases/tag/v3.16.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: