fix: include default workerpool in list
terraform-ibm-modules/terraform-ibm-base-ocp-vpc pull request #383
Opened 2024-03-04 21:17 UTC by kierramarie

### Description

 The default worker pool was not originally included in the "workerpools" output variable. It has been updated to include it now.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-03-04 21:17 UTC, kierramarie commented
/run pipeline

2024-03-04 21:26 UTC, kierramarie commented
/run pipeline

2024-03-05 18:20 UTC, kierramarie commented
/run pipeline

2024-03-05 20:27 UTC, kierramarie commented
/run pipeline

2024-03-05 22:43 UTC, jor2 submitted a review, later dismissed

2024-03-05 22:43 UTC, jor2 commented
https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/367

2024-03-06 19:26 UTC, toddgiguere requested changes

2024-03-06 19:26 UTC, toddgiguere commented on outputs.tf
> +  value       = merge(data.ibm_container_vpc_worker_pool.default_pool, var.ignore_worker_pool_size_changes ? ibm_container_vpc_worker_pool.autoscaling_pool : ibm_container_vpc_worker_pool.pool)
Spoke with author, we are going to try to do this with a single data block representing all pools to ensure that the final object blocks will always match.

2024-03-06 20:56 UTC, kierramarie commented
/run pipeline

2024-03-06 21:07 UTC, kierramarie commented
/run pipeline

2024-03-06 21:42 UTC, kierramarie commented
/run pipeline

2024-03-15 11:58 UTC, toddgiguere approved these changes

2024-03-15 12:01 UTC, toddgiguere commented
/run pipeline

2024-03-15 14:09 UTC, merged

2024-03-15 14:10 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 3.20.1 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/releases/tag/v3.20.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: