feat: support for ocp v4.15
terraform-ibm-modules/terraform-ibm-base-ocp-vpc pull request #423
Opened 2024-04-30 13:08 UTC by Aashiq-J

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-04-30 13:13 UTC, Aashiq-J commented
/run pipeline

2024-05-02 16:01 UTC, ocofaigh requested changes
please update the tests accordingly so they test 4.15

2024-05-02 16:01 UTC, ocofaigh commented on variables.tf
> +  description = "Whether to allow public outbound access from the cluster workers."
you should mention this is only applicable for 4.15

2024-05-03 08:27 UTC, Aashiq-J commented
/run pipeline

2024-05-03 11:21 UTC, vburckhardt commented
Couple of invalid version error
```
TestRunUpgradeAdvancedExample 2024-05-03T08:35:17Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: Invalid value for variable
│ 
│   on main.tf line 160, in module "ocp_base":
│  160:   ocp_version          = var.ocp_version
│     ├────────────────
│     │ var.ocp_version is "4.15"
│ 
│ The specified ocp_version is not of the valid versions.
│ 
│ This was checked by the validation rule at ../../variables.tf:156,3-13
```.

2024-05-03 12:15 UTC, vburckhardt commented
/run pipeline

2024-05-03 12:42 UTC, Aashiq-J commented
@vburckhardt , @ocofaigh 
Should i skip the upgrade test for this PR, the error is due to the pipeline running example with version 4.15 in main branch which doesn't have the updated validation.

2024-05-03 14:13 UTC, vburckhardt approved these changes

2024-05-03 14:13 UTC, merged

2024-05-03 14:14 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 3.21.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/releases/tag/v3.21.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: