feat: added operating-system input variable
terraform-ibm-modules/terraform-ibm-base-ocp-vpc pull request #436
Opened 2024-05-20 14:32 UTC by Khuzaima05

### Description
Add operating-system input variable for OCP 4.15 and beyond (RHCoreOS now an option)

issue: https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/429

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-05-20 14:32 UTC, Khuzaima05 commented
/run pipeline

2024-05-21 12:38 UTC, Khuzaima05 commented
/run pipeline

2024-05-22 07:35 UTC, Khuzaima05 commented
Pipeline is failing with the following error:

`Error: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"524af746-bd3d-4e16-9883-9ee890cc7813,524af746-bd3d-4e16-9883-9ee890cc7813","code":"E1437","description":"The action cannot be completed because it would reduce the worker pool size to below the cluster's minimum requirement of 2 workers.","type":"BadRequest"}`

Other [PR](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/actions/runs/9174824931/job/25226696386#step:7:4409) pipeline also facing same error.

2024-05-24 15:30 UTC, Khuzaima05 commented
/run pipeline

2024-05-26 21:27 UTC, ocofaigh commented on variables.tf
> +  description = "The operating system of the workers in the default worker pool."
can you include in the description what the behaviour is when value is not set?

2024-05-29 09:20 UTC, Khuzaima05 commented
/run pipeline

2024-05-30 16:44 UTC, ocofaigh commented on variables.tf
> +  description = "The operating system of the workers in the default worker pool. If no value is specified, RHEL 8 will be used as the default."
surely it won't always be RHEL 8. I guess it will default to whatever the current default OS is.

2024-05-30 16:44 UTC, ocofaigh requested changes
This needs to be exposed in fscloud submodule too

2024-06-04 06:27 UTC, Khuzaima05 commented
/run pipeline

2024-06-05 08:53 UTC, Khuzaima05 commented
/run pipeline

2024-06-05 12:07 UTC, Khuzaima05 commented
/run pipeline

2024-06-06 09:28 UTC, ocofaigh approved these changes

2024-06-06 09:29 UTC, merged

2024-06-06 09:30 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 3.25.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/releases/tag/v3.25.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-06-17 11:01 UTC, vburckhardt reviewed
Missing the aspect about pool - https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_vpc_worker_pool#operating_system

2024-06-25 10:28 UTC, imprateeksh commented on variables.tf
> +}
This will be addressed in the [PR-466](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/466)